/* Auto-generated by manage.py - DO NOT EDIT */
import type { InfiniteCanvas } from './components/infinite-canvas/index';
import type { ListView } from './components/list-view/index';
import type { ListWindow } from './components/list-window/index';
import type { SizeModifier } from './components/size-modifier/index';
import type { TabView } from './components/tab-view/index';
import type { TemplateGenerator } from './components/template-generator/index';

declare global {
  interface HTMLElementTagNameMap {
    'infinite-canvas': InfiniteCanvas;
    'list-view': ListView;
    'list-window': ListWindow;
    'size-modifier': SizeModifier;
    'tab-view': TabView;
    'template-generator': TemplateGenerator;
  }
}
