/* Auto-generated by manage.py - DO NOT EDIT */
import type { InfiniteCanvas } from '@components/infinite-canvas'
import type { ListView } from '@components/list-view'
import type { ListWindow } from '@components/list-window'
import type { SizeModifier } from '@components/size-modifier'
import type { TabView } from '@components/tab-view'
import type { TemplateGenerator } from '@components/template-generator'

declare global {
  interface HTMLElementTagNameMap {
    'infinite-canvas': InfiniteCanvas;
    'list-view': ListView;
    'list-window': ListWindow;
    'size-modifier': SizeModifier;
    'tab-view': TabView;
    'template-generator': TemplateGenerator;
  }
}
